robot: # namespace
  state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50 # Hz, frequenia

  MY_WHEEL_ONE_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE

  MY_WHEEL_TWO_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO

  MY_WHEEL_THREE_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE

  MY_WHEEL_ONE_RODETA_1_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_1_joint

  MY_WHEEL_ONE_RODETA_2_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_2_joint

  MY_WHEEL_ONE_RODETA_3_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_3_joint

  MY_WHEEL_ONE_RODETA_4_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_4_joint

  MY_WHEEL_ONE_RODETA_5_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_5_joint

  MY_WHEEL_ONE_RODETA_6_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_6_joint

  MY_WHEEL_ONE_RODETA_7_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_7_joint

  MY_WHEEL_ONE_RODETA_8_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_8_joint

  MY_WHEEL_ONE_RODETA_9_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_9_joint  

  MY_WHEEL_ONE_RODETA_10_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_10_joint 

  MY_WHEEL_ONE_RODETA_11_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_11_joint 

  MY_WHEEL_ONE_RODETA_12_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_12_joint 

  MY_WHEEL_ONE_RODETA_13_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_13_joint 

  MY_WHEEL_ONE_RODETA_14_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_14_joint 

  MY_WHEEL_TONE_RODETA_15_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_15_joint 

  MY_WHEEL_ONE_RODETA_16_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_ONE_rodeta_16_joint   
   
  MY_WHEEL_TWO_RODETA_1_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_1_joint

  MY_WHEEL_TWO_RODETA_2_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_2_joint

  MY_WHEEL_TWO_RODETA_3_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_3_joint

  MY_WHEEL_TWO_RODETA_4_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_4_joint

  MY_WHEEL_TWO_RODETA_5_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_5_joint

  MY_WHEEL_TWO_RODETA_6_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_6_joint

  MY_WHEEL_TWO_RODETA_7_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_7_joint

  MY_WHEEL_TWO_RODETA_8_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_8_joint

  MY_WHEEL_TWO_RODETA_9_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_9_joint  

  MY_WHEEL_TWO_RODETA_10_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_10_joint 

  MY_WHEEL_TWO_RODETA_11_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_11_joint 

  MY_WHEEL_TWO_RODETA_12_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_12_joint 

  MY_WHEEL_TWO_RODETA_13_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_13_joint 

  MY_WHEEL_TWO_RODETA_14_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_14_joint 

  MY_WHEEL_TWO_RODETA_15_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_15_joint 

  MY_WHEEL_TWO_RODETA_16_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_TWO_rodeta_16_joint    

  MY_WHEEL_THREE_RODETA_1_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_1_joint

  MY_WHEEL_THREE_RODETA_2_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_2_joint

  MY_WHEEL_THREE_RODETA_3_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_3_joint

  MY_WHEEL_THREE_RODETA_4_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_4_joint

  MY_WHEEL_THREE_RODETA_5_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_5_joint

  MY_WHEEL_THREE_RODETA_6_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_6_joint

  MY_WHEEL_THREE_RODETA_7_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_7_joint

  MY_WHEEL_THREE_RODETA_8_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_8_joint   

  MY_WHEEL_THREE_RODETA_9_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_9_joint  

  MY_WHEEL_THREE_RODETA_10_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_10_joint 

  MY_WHEEL_THREE_RODETA_11_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_11_joint 

  MY_WHEEL_THREE_RODETA_12_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_12_joint 

  MY_WHEEL_THREE_RODETA_13_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_13_joint 

  MY_WHEEL_THREE_RODETA_14_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_14_joint 

  MY_WHEEL_THREE_RODETA_15_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_15_joint 

  MY_WHEEL_THREE_RODETA_16_CONTROLLER:
     type: effort_controllers/JointEffortController
     joint: MY_WHEEL_THREE_rodeta_16_joint  

  HELIX_ORIENTATION_CONTROLLER:
     type: position_controllers/JointTrajectoryController
     joints: 
      - rev1
      - rev2

  TOP_PROPELLER_CONTROLLER:
     type: velocity_controllers/JointVelocityController
     joint: top_propeller  

  BOTTOM_PROPELLER_CONTROLLER:
     type: velocity_controllers/JointVelocityController
     joint: bottom_propeller       
